version: '3.8'

services:
  # Frontend Angular uniquement
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: sogood-frontend